spring:
  application:
    name: hotelBookingService

  datasource:
    url: jdbc:postgresql://localhost:5435/root
    username: root
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

grpc:
  server:
    port: 9099

server:
  port: 8081